# Generated by Django 5.0.6 on 2024-10-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content",
            field=models.TextField(null=True),
        ),
    ]
