# Generated by Django 5.1.2 on 2025-01-06 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="main_content",
        ),
    ]
