# Generated by Django 5.0.6 on 2024-10-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_article_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
