# Generated by Django 5.1.2 on 2024-10-24 11:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_author_pen_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="main_content",
            field=ckeditor.fields.RichTextField(default=""),
        ),
    ]
