# Generated by Django 5.1.2 on 2024-10-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_article_main_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="content",
        ),
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
