# Generated by Django 5.1.2 on 2024-11-13 16:44

import django.db.models.deletion
import prose.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_article_main_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", prose.fields.DocumentContentField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="article",
            name="excerpt",
            field=prose.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="body",
            field=models.OneToOneField(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.articlecontent",
            ),
        ),
    ]
