# Generated by Django 5.1.2 on 2024-11-13 16:46

import prose.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_articlecontent_article_excerpt_article_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="body",
        ),
        migrations.RemoveField(
            model_name="article",
            name="excerpt",
        ),
        migrations.AddField(
            model_name="article",
            name="content",
            field=prose.fields.RichTextField(default=""),
        ),
        migrations.DeleteModel(
            name="ArticleContent",
        ),
    ]
